### PR TITLE
A very simple demo game

### PR DESCRIPTION
**Pull request by felipenmartins**
This program implements a very simple game with all robots. It serves as a crude example of how the games will run.

### CODE REVIEW

**Comment by felipenmartins** [comment]
@mrshu and @Adman , could you check if the addition of this example code makes sense? And, if so, make it available in the main branch?
Since we already publicized the github of the soccer sim, I think it would help if teams could see a (simple) game play as a crude example.

**Comment by Adman** [comment]
As I'm now thinking about this, we should probably create 6 separate files, each for one robot. In terms of example program, we could create some Abstract class to put common logic there and instantiate each robot's program with this class. This will require to redefine script names in the world file. So we won't confuse participants that it is put into one file. What do you think about this?

**Comment by felipenmartins** [comment]
> As I'm now thinking about this, we should probably create 6 separate files, each for one robot. In terms of example program, we could create some Abstract class to put common logic there and instantiate each robot's program with this class. This will require to redefine script names in the world file. So we won't confuse participants that it is put into one file. What do you think about this?

Well, you are programmers. So, if you think you can do it, I am all for it! 👍 
I just wanted to give team a simple toy team to play against and use as example.
When do you think you can have this available?

**Comment by mrshu** [comment]
@Adman the way I see it, this would probably be OK, provided that we create that Abstract class--otherwise there is a good chance we may be over-complicating it (and generally raising the bar for entry, which I think would be rather unfortunate).

That said, I do agree that we should aim to create 6 files here, since that is what we'll expect the teams to submit anyway.

@felipenmartins looking at the changes, it seems like most of them amount to changing of variables. I believe we ought to be able to put something similar together on Monday.

**Comment by felipenmartins** [comment]
@mrshu and @Adman Great! Thanks! :-)

**Comment by Adman** [comment]
@mrshu Wouldn't it be better that teams submit entire zip file with code, which would contain 3 files for robots (with names like `robot_a.py`, `robot_b.py` and `robot_c.py` + some helper python scripts/functions located in other python files?

**Comment by mrshu** [comment]
@Adman That would indeed be great!

The only slight update would be that I would like it to be an open Git repository, which we can just `git clone`. The folder structure then could be something on the order of

```bash
$ git clone https://github.com/teamA/simulated-soccer.git teamA
$ tree teamA
teamA/
├── robot1
│   └── robot1.py
├── robot2
│   └── robot2.py
├── robot3
│   └── robot3.py
└── utils
    └── rcj_serializer.py
```

Our automation would then appropriately map this in the Webots world, so that the whole simulation can actually run.

Would that make sense?

**Comment by mrshu** [comment]
Also, it seems like we can close this PR in lieu #30

**Comment by Adman** [comment]
See my comment about directory structure in #30

**Pull request closed without merging**
